title: sinri.github.io
description: GitHub Pages
url: https://sinri.github.io
baseurl: ""
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-optional-front-matter
markdown: kramdown
kramdown:
  input: GFM
permalink: /:categories/:year/:month/:day/:title/
timezone: Asia/Shanghai
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .idea
  - .vscode
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
