title: sinri.github.io
description: The publications by Sinri Edogawa on GitHub Pages
url: https://sinri.github.io
baseurl: ""
encoding: utf-8
# theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-relative-links
markdown: kramdown
kramdown:
  input: GFM
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
relative_links:
  enabled: true
  include: ["reels"]
  exclude: ["iOS","StrongDict"]
permalink: /:title/

# Rerun `bundle exec jekyll serve --livereload` after mofifying this file.